export const ADD_BOOK = 'add_book'
export const AUTH_USER = 'auth_user'
export const UNAUTH_USER = 'unauth_user'    
export const AUTH_ERROR = 'auth_error'
export const FETCH_MESSAGE = 'fetch_message'
export const GET_ALL_BOOKS = 'get_all_books'
export const GET_MY_BOOKS = 'get_my_books'
export const GET_REQ_BOOKS = 'get_req_books'